### ISSUE TITLE
Dibujo

### ISSUE THREAD

**Issue by BorquezBelli** [pdepjm/2023-tp0-presentacion-marianoSLamaison#1]
Que onda lo del dibujo? Tenes fotos o algo para subir? Admiro la gente que tiene facilidad para dibujar

**Comment by marianoSLamaison** [comment]
Tengo esta que hice en un cursito web de dibujo hace un tiempo no lo pude terminar por la universidad, este año vere si puedo apartarme un tiempo para terminarlo.
![photo_2023-04-03_00-25-19](https://user-images.githubusercontent.com/126605894/229404850-4a538a34-6eeb-4194-8223-4659d561cbb7.jpg)
